apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend-service
  namespace: portfolio-staging
spec:
  selector:
    app: portfolio-backend
  ports:
  - port: 8000
    targetPort: 8000
  type: ClusterIP
